version: '3'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db_glab
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
    ports:
    - 26432:5432

#  app:
#    build: ./app
#    command: sh -c "python manage.py runserver 0.0.0.0:8001"
#    container_name: app_glab
#    volumes:
#      - ./app/:/app/
#    ports:
#      - 8002:8000
#    env_file:
#      - ./app/.env
#    depends_on:
#      - db

volumes:
  postgres_data: