# Generated by Django 3.1.3 on 2020-11-17 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade de pessoas'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='n_computers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Computadores'),
        ),
    ]
