# Generated by Django 2.2.5 on 2019-11-09 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191105_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Laboratório', 'verbose_name_plural': 'Laboratórios'},
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='n_computers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Computadores'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome'),
        ),
    ]
