# Generated by Django 2.2.5 on 2019-11-06 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191105_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('367bf0d3-ac32-4449-a7a4-8fa0757599ac'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('E', 'Estudante'), ('P', 'Professor')], max_length=1, verbose_name='User Type'),
        ),
    ]
