# Generated by Django 2.2.5 on 2019-11-09 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191108_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38fc5f96-c624-4101-b66b-df4b88a5f625'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
