# Generated by Django 2.2.5 on 2019-11-12 04:04

import apps.users.utils
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191108_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criação da Conta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False, verbose_name='Email Confirmado Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11e6dc11-feb3-4ae0-9254-90e69de5d0f2'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Status Equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=apps.users.utils.UploadToFactory('users/user/profile-picture'), verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_email',
            field=models.BooleanField(default=False, verbose_name='Compartilhar Email Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_phone',
            field=models.BooleanField(default=False, verbose_name='Compartilhar Telefone Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('E', 'Estudante'), ('P', 'Professor')], max_length=1, verbose_name='Tipo de Usuário'),
        ),
    ]
