# Generated by Django 2.2.5 on 2019-11-12 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191111_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f325e4e3-d5c0-406a-812c-4b36120020e1'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
