# Generated by Django 2.2.5 on 2019-11-12 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191111_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac0d7f77-e350-40e4-b150-d9cfa30d5920'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
