# Generated by Django 2.2.5 on 2019-11-12 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191111_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97ce1328-274a-4a4e-80eb-e6decee86e64'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
