# Generated by Django 2.2.5 on 2019-11-05 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('initial_time', models.DateTimeField(verbose_name='Initial Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(max_length=1, verbose_name='Status')),
                ('obs', models.TextField(max_length=255, verbose_name='Obs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_set', to='base.Laboratory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
