# Generated by Django 2.2.5 on 2019-11-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='initial_time',
            field=models.TimeField(verbose_name='Initial Time'),
        ),
    ]
