# Generated by Django 2.2.5 on 2019-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20191108_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='end_time',
            field=models.TimeField(verbose_name='Hora Termino'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='initial_time',
            field=models.TimeField(verbose_name='Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='obs',
            field=models.TextField(max_length=255, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[(1, 'Aguardando Resposta'), (2, 'Utilização Negada'), (3, 'Utilização Aceita'), (4, 'Utilizado')], max_length=1, verbose_name='Status'),
        ),
    ]
