# Generated by Django 2.2.5 on 2019-11-12 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_auto_20191111_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_set', to='base.Laboratory', verbose_name='Laboratório'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_set', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
    ]
