# Generated by Django 2.2.5 on 2019-11-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_auto_20191111_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('1', 'Aguardando Resposta'), ('2', 'Utilização Negada'), ('3', 'Utilização Aceita'), ('4', 'Utilizado')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
